/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author Julia
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Letra1 = new javax.swing.JCheckBox();
        Letra2 = new javax.swing.JCheckBox();
        Letra3 = new javax.swing.JCheckBox();
        Letra4 = new javax.swing.JCheckBox();
        Letra5 = new javax.swing.JCheckBox();
        Letra6 = new javax.swing.JCheckBox();
        Letra7 = new javax.swing.JCheckBox();
        ValidarTiro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CambioLetra = new javax.swing.JButton();
        ValidarTiro1 = new javax.swing.JButton();
        Letras1 = new javax.swing.JButton();
        Letras2 = new javax.swing.JButton();
        Letras3 = new javax.swing.JButton();
        Letras4 = new javax.swing.JButton();
        Letras5 = new javax.swing.JButton();
        Letras6 = new javax.swing.JButton();
        Letras7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista de Fichas Activas", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista Diccionario", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Matriz Tablero", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cola de Fichas", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista Jugadores", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(630, 0, 300, 660);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Pestanias");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 30, 140, 30);
        jLabel1.getAccessibleContext().setAccessibleName("NombreJugador");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Turno de:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 0, 90, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Cambiar Letras");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 410, 140, 30);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 100, 160, 160);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Puntuaciones");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 60, 120, 30);

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 320, 160, 30);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Cambiar");
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 590, 130, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Nueva Palabra");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 280, 140, 30);

        Letra1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra1);
        Letra1.setBounds(460, 450, 40, 21);

        Letra2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra2);
        Letra2.setBounds(550, 450, 70, 23);

        Letra3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra3);
        Letra3.setBounds(460, 480, 70, 23);

        Letra4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra4);
        Letra4.setBounds(550, 480, 70, 23);

        Letra5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra5);
        Letra5.setBounds(460, 510, 70, 23);

        Letra6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra6);
        Letra6.setBounds(550, 510, 70, 23);

        Letra7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(Letra7);
        Letra7.setBounds(500, 540, 50, 23);

        ValidarTiro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ValidarTiro.setText("Validar Tiro");
        ValidarTiro.setToolTipText("");
        getContentPane().add(ValidarTiro);
        ValidarTiro.setBounds(60, 590, 130, 40);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Letras Activas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 470, 130, 30);

        CambioLetra.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CambioLetra.setText("Agregar Palabra");
        getContentPane().add(CambioLetra);
        CambioLetra.setBounds(470, 360, 130, 40);

        ValidarTiro1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ValidarTiro1.setText("Validar Tiro");
        ValidarTiro1.setToolTipText("");
        getContentPane().add(ValidarTiro1);
        ValidarTiro1.setBounds(260, 590, 130, 40);
        getContentPane().add(Letras1);
        Letras1.setBounds(380, 520, 50, 40);
        getContentPane().add(Letras2);
        Letras2.setBounds(20, 520, 50, 40);
        getContentPane().add(Letras3);
        Letras3.setBounds(80, 520, 50, 40);
        getContentPane().add(Letras4);
        Letras4.setBounds(140, 520, 50, 40);
        getContentPane().add(Letras5);
        Letras5.setBounds(200, 520, 50, 40);
        getContentPane().add(Letras6);
        Letras6.setBounds(260, 520, 50, 40);
        getContentPane().add(Letras7);
        Letras7.setBounds(320, 520, 50, 40);

        jPanel6.setMinimumSize(new java.awt.Dimension(360, 360));
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 420));
        jPanel6.setLayout(null);

        jButton2.setText("jButton2");
        jPanel6.add(jButton2);
        jButton2.setBounds(172, 47, 73, 23);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 40, 420, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambioLetra;
    private javax.swing.JCheckBox Letra1;
    private javax.swing.JCheckBox Letra2;
    private javax.swing.JCheckBox Letra3;
    private javax.swing.JCheckBox Letra4;
    private javax.swing.JCheckBox Letra5;
    private javax.swing.JCheckBox Letra6;
    private javax.swing.JCheckBox Letra7;
    private javax.swing.JButton Letras1;
    private javax.swing.JButton Letras2;
    private javax.swing.JButton Letras3;
    private javax.swing.JButton Letras4;
    private javax.swing.JButton Letras5;
    private javax.swing.JButton Letras6;
    private javax.swing.JButton Letras7;
    private javax.swing.JButton ValidarTiro;
    private javax.swing.JButton ValidarTiro1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
