/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jdom.Document;         // |
import org.jdom.Element;          // |\ Librerías
import org.jdom.JDOMException;    // |/ JDOM
import org.jdom.input.SAXBuilder; // |

/**
 *
 * @author Julia
 */
public class Ventana1 extends javax.swing.JFrame {

    boolean empezo;
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        empezo=false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Leer Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 110, 130, 40);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setText("Jugar");
        jButton2.setActionCommand("jugar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 110, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1/scrabble.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String ruta;
    String linea;
    String TodoContenido;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file=new JFileChooser();
        file.showOpenDialog(this);
        File abre=file.getSelectedFile();
        ruta = abre.getPath();
        if (abre != null) {
            FileReader archivos = null;
            try {
                archivos = new FileReader(abre);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader lee = new BufferedReader(archivos);
            try {
                TodoContenido="";
                while ((linea = lee.readLine()) != null) {
                    TodoContenido=TodoContenido+linea;
                }
            } catch (IOException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                lee.close();
            } catch (IOException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        AnalizarArchivo(TodoContenido);
        empezo=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(empezo=true){
            Jugadores juegan=new Jugadores();
            juegan.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public static int Tamanio;
    public static CasillasExtras Dobles =new CasillasExtras();
    public static CasillasExtras Triples =new CasillasExtras();
    public static Diccionario Palabras = new Diccionario();
    
    public void AnalizarArchivo(String contenido){
        contenido=contenido.replaceAll("<scrabble>","");
        contenido=contenido.replaceAll("</scrabble>", "");
        contenido=contenido.replaceAll("<dimension>", "");
        contenido=contenido.replaceAll("</dimension>","");;
        String[] contenido2=contenido.split("<dobles>");
        Tamanio=Integer.parseInt(contenido2[0]);
        contenido2=contenido2[1].split("</dobles>");
        contenido2[0]=contenido2[0].replaceAll("<casilla>", "");
        String[] contenido3=contenido2[0].split("</casilla>");
        String contenido4;
        String[] contenido5;
        for(int i = 0; i<contenido3.length;i++){
            contenido4=contenido3[i].replaceAll("<x>", "");
            contenido4=contenido4.replaceAll("<y>", "");
            contenido4=contenido4.replaceAll("</y>", "");
            contenido5=contenido4.split("</x>");
            Dobles.InsertarCasilla(Integer.parseInt(contenido5[0]), Integer.parseInt(contenido5[1]));
        }
        String contenido6=contenido2[1].replaceAll("<triples>", "");
        String[] contenido7=contenido6.split("</triples>");
        contenido7[0]=contenido7[0].replaceAll("<casilla>","");
        String[] contenido8=contenido7[0].split("</casilla>");
        String contenido9;
        String[] contenido10;
        for(int i = 0; i<contenido8.length;i++){
            contenido9=contenido8[i].replaceAll("<x>", "");
            contenido9=contenido9.replaceAll("<y>", "");
            contenido9=contenido9.replaceAll("</y>", "");
            contenido10=contenido9.split("</x>");
            Triples.InsertarCasilla(Integer.parseInt(contenido10[0]), Integer.parseInt(contenido10[1]));
        }
        contenido7[1]=contenido7[1].replaceAll("<diccionario>", "");
        contenido7[1]=contenido7[1].replaceAll("</diccionario>", "");
        contenido7[1]=contenido7[1].replaceAll("<palabra>", "");
        String[] contenido11=contenido7[1].split("</palabra>");
        for(int i=0;i<contenido11.length;i++){
            Palabras.InsertarPalabra(contenido11[i]);
        }
        Dobles.RecorrerCasillas();
        Triples.RecorrerCasillas();
        Palabras.mostrarPalabras();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
